# Generated by Django 3.1.2 on 2020-10-30 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pooltable',
            old_name='clean',
            new_name='clean_rating',
        ),
        migrations.RenameField(
            model_name='pooltable',
            old_name='damage',
            new_name='damage_rating',
        ),
        migrations.RenameField(
            model_name='pooltable',
            old_name='number',
            new_name='table_number',
        ),
    ]
