# Generated by Django 3.1.2 on 2020-10-25 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20201025_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='alcoholic',
            field=models.BooleanField(default=1),
        ),
    ]
